config/routes.rb
Rails.application.routes.draw do


  mount Ckeditor::Engine => '/ckeditor'
  namespace :index do
    get 'home/index'
    get 'article/:title' => 'home#show',title: /[^\/]+/,as: :article
  end

  root 'index/home#index'
  get '/u/:user' => "index/users#index"
  get '/u/:user/tag/:name' => "index/users#tag"
  get '/u/:user/category/:name' => 'index/users#category'
  post '/search' => 'index/home#search'
  post '/search/:user' => 'index/users#search'
  get '/article-type/:name' => 'index/home#article_type'
  namespace :manage do
    get '/' => "index#index"
    get 'login' => 'session#new'
    post 'login' => 'session#create'
    delete 'login' => 'session#destroy'
    resources :users
    resources :authors
    resources :article_types
  end

  namespace :admin do
    get '/' => "index#index"
    get 'index/index'
    get 'login' => 'session#new'
    post 'login' => 'session#create'
    delete 'logout' => 'session#destroy'
    get 'category/:name' => 'articles#category'
    get 'tag/:name' => 'articles#tag'
    get 'archive/:year/:month' => 'articles#archive'
    resources :archives
    resources :categories
    resources :tags
    resources :articles
    resources :messages
    resources :authors,only:[:index,:edit,:update,:show]
    get 'repassword' => 'authors#repassword'
    post 'repassword' => 'authors#update_password'
    post 'mdtools/preview' => 'mdtools#preview'
  end

  namespace :api do
    post 'push_article' => 'article#index'
  end
end

app/models/admin/article.rb
class Admin::Article < ActiveRecord::Base
  has_and_belongs_to_many :categories
  has_and_belongs_to_many :tags
  belongs_to :article_type, :class_name => 'Admin::ArticleType'
  belongs_to :author
  belongs_to :archive

  attr_accessor :tag_names
  attr_accessor :category_ids

  validates :title,presence:true,uniqueness:true
  before_create :strip
  before_save :set_abstract

  def strip
    self.title = self.title.lstrip
  end

  def set_abstract
    labels = /(```[A-Za-z]*)|(``)|(`)|(^>+)|(\*\*)|(\[\^\d\])|(#+ )/
    self.abstract = self.content[0..300].gsub(labels,"")
  end

  def state
    return "已发布" if status == 1
    return "未发布" if status == 0
  end

  def add_categories
    categories.clear
    category_ids.each{|id| add_category(id)} if category_ids
  end

  def add_tags(author_id)
    tags.clear
    tag_names.each {|t| add_tag(t,author_id)} if tag_names
    tags = tags.uniq if tags
  end

  private
  def add_tag(tagName,author_id)
    current_tag = Admin::Tag.find_or_create_by(name:tagName,author_id:author_id)
    tags<<current_tag if current_tag.save
  end

  def add_category(categoryId)
    current_category = Admin::Category.find_by_id(categoryId)
    categories<<current_category if current_category
  end


end

app/models/admin/article_type.rb
class Admin::ArticleType < ActiveRecord::Base
  has_many :articles
  mount_uploader :img, Admin::ArticleTypeImgUploader
end

app/models/admin/author.rb
class Admin::Author < ActiveRecord::Base
  has_secure_password
  mount_uploader :avatar, Admin::AuthorAvatarUploader
  has_many :archives
  has_many :articles
  has_many :categories
  has_many :tags
  validates :name,presence: true,
                  length: { minimum: 2,maximum: 10 },
                  uniqueness: { value:true, case_sensitive: false }
  before_create :strip

  def strip
    self.name = self.name.lstrip
  end
end

app/controllers/admin/articles_controller.rb
class Admin::ArticlesController < AdminController
  before_action :set_admin_article, only: [:show, :edit, :update, :destroy]
  before_action :set_all_category, only: [:new, :edit, :update, :create]
  before_action :set_all_article_type, only: [:new, :edit, :update, :create]

  # GET /admin/articles
  # GET /admin/articles.json
  def index
    @admin_articles = @login_author.articles.order("created_at DESC")
  end

  def category
    @admin_articles = (category = @login_author.categories.find_by_name(params[:name])) && category.articles
    render :index
  end

  def tag
    @admin_articles = (tag = @login_author.tags.find_by_name(params[:name])) && tag.articles
    render :index
  end

  def archive
    @admin_articles = (archive = @login_author.archives.where(year:params[:year],month:params[:month])[0]) && archive.articles
    render :index
  end
  # GET /admin/articles/1
  # GET /admin/articles/1.json
  def show
  end

  # GET /admin/articles/new
  def new
    @admin_article = Admin::Article.new
    if params[:editor] && params[:editor] == "ckeditor"
      @editor_type = 1
    else
      @editor_type = 0
    end
  end

  # GET /admin/articles/1/edit
  def edit
    if params[:editor] && params[:editor] == "ckeditor"
      @editor_type = 1
    else
      @editor_type = 0
    end
  end

  def preview
    @preview_text = params[:text]
    respond_to do |format|
      if @preview_text
        format.js {}
        format.json { render :edit, status: :previewed, location: @preview_text }
      else
        format.json { render json: @preview_text, status: :unprocessable_entity }
      end
    end
  end
  # POST /admin/articles
  # POST /admin/articles.json
  def create
    @admin_article = Admin::Article.new(admin_article_params)
   
    add_author_tags_categories_archive
    respond_to do |format|
      if @admin_article.save
        format.html { redirect_to admin_articles_path, notice: '已创建.' }
        format.json { render :show, status: :created, location: @admin_article }
      else
        format.html { render :new }
        format.json { render json: @admin_article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin/articles/1
  # PATCH/PUT /admin/articles/1.json
  def update
    respond_to do |format|
      if @admin_article.update(admin_article_params)
        update_author_tags_categories
        format.html { redirect_to admin_articles_path, notice: '已更新.' }
        format.json { render :show, status: :ok, location: @admin_article }
      else
        format.html { render :edit }
        format.json { render json: @admin_article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/articles/1
  # DELETE /admin/articles/1.json
  def destroy
    @admin_article.destroy
    respond_to do |format|
      format.html { redirect_to admin_articles_url, notice: '已删除.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_admin_article
      @admin_article = @login_author.articles.find_by_id(params[:id])
      if @admin_article.nil?
        render html: "<strong>Not Found</strong>".html_safe and return
      end
    end

  def set_all_article_type

    @all_article_types = []
    all_article_types = Admin::ArticleType.all
    all_article_types.each {|t| @all_article_types << [t.name,t.id]}
  end
  def set_all_category
    @all_categories = []
    if @login_author.categories.where(supcategory_id: nil)
      @login_author.categories.where(supcategory_id: nil).each {|c| dfs(@all_categories,0,c)}
    end
  end

  def dfs(all_categories,level,node)
    node.level = level
    all_categories.push(node)
    return if node.subcategories.count==0

    level += 1
    node.subcategories.each do |c|
      dfs(all_categories,level,c)
    end
  end

  def add_author_tags_categories_archive
    @admin_article.author_id = @login_author.id
    @admin_article.tag_names = params["admin_article"]["tag_names"].split(',')
    @admin_article.category_ids = params["admin_article"]["category_ids"]
    archive = Admin::Archive.find_or_create_by(author_id:@login_author.id,year:Time.now.year,month:Time.now.month)
    @admin_article.archive_id = archive.id
    @admin_article.add_categories
    @admin_article.add_tags(@login_author.id)
  end

  def update_author_tags_categories
    @admin_article.tag_names = params["admin_article"]["tag_names"].split(',')
    @admin_article.category_ids = params["admin_article"]["category_ids"]
    @admin_article.add_categories
    @admin_article.add_tags(@login_author.id)
  end
    # Never trust parameters from the scary internet, only allow the white list through.
    def admin_article_params
      params.require(:admin_article).permit(:title, :content, :tag_names, :category_ids, :article_type_id, :editor)
    end
end

app/controllers/api/article_controller.rb
class Api::ArticleController < ApiController
  before_action :check_user
  def index
    @article = Admin::Article.find_by_title(params[:title])
    if @article
      respond_to do |format|
        update_author_tags_categories
        if @article.update(title:params[:title],content:params[:content],article_type_id:params[:type])
          format.json { render nothing: true, status: 200, location: @article }
        else
          format.json { render json: @article.errors, status: :unprocessable_entity }
        end
      end
    else
      @article = Admin::Article.new(title:params[:title],content:params[:content],article_type_id:params[:type])
      respond_to do |format|
        add_author_tags_categories_archive
        if @article.save
          format.json { render nothing: true, status: 200, location: @article }
        else
          format.json { render json: @article.errors, status: :unprocessable_entity }
        end
      end
    end
  end
  private
    def check_user
      @author = Admin::Author.find_by_name(params[:name])
      if !(@author && @author.authenticate(params[:password]))
        return false
      end
    end

    def add_author_tags_categories_archive
      @article.author_id = @author.id
      @article.tag_names = params["tags"].split(',')
      category_ids = params["categories"].split(',').map{|name| @author.categories.find_by_name(name)}.compact
      @article.category_ids = category_ids.map{|cat| cat.id}
      archive = Admin::Archive.find_or_create_by(author_id:@author.id,year:Time.now.year,month:Time.now.month)
      @article.archive_id = archive.id
      @article.add_categories
      @article.add_tags(@author.id)
    end

    def update_author_tags_categories
      @article.tag_names = params["tags"].split(',')
      category_ids = params["categories"].split(',').map{|name| @author.categories.find_by_name(name)}.compact
      @article.category_ids = category_ids.map{|cat| cat.id}
      @article.add_categories
      @article.add_tags(@author.id)
    end
end

app/helpers/admin/articles_helper.rb
module Admin::ArticlesHelper
end

app/helpers/api/article_helper.rb
module Api::ArticleHelper
end

app/views/admin/articles/_form.html.erb
<%= form_for(@admin_article) do |f| %>
    <%= form_errors(@admin_article) %>

    <div class="main-form">
        <div class="form-group">
          <%= f.text_field :title, class:"form-control",placeholder:"请输入标题" %>
        </div>
        
        <section class="md-tools-bar">
          <div class="md-tools-group right">
            <span id="tool-preview" class="glyphicon glyphicon-eye-open item"></span>
          </div>

        </section>
        
        <div class="form-group">
          <%= f.text_area :content,id:"preview_text",class:"form-control",placeholder:"支持Markdown语法" %>
        </div>
        <div class="form-group" id="side-preview"></div>
        <%= f.text_field :editor,value: 0,class:"sr-only" %>

        <div class="form-group action">
          <%= link_to '取消', admin_articles_path,class:"btn btn-default cancle" %>
          <%= f.submit class:"btn btn-primary submit",id:"submit" %>
        </div>
    </div>
    <div class="related-form">
      <%= f.label "分类" %>
      <div class="category form-group">
        <% @all_categories.each do |c| %>
          <label class="checkbox">
            <!-- <%= ("&nbsp&nbsp"*c.level).html_safe %> -->
            <%= check_box_tag "admin_article[category_ids][]",c.id,@admin_article.categories.include?(c),{multiple:true,'data-toggle' => "checkbox"} %><%= ">>"*c.level %><b><%= c.name %></b><br>
          </label>
        <% end %>
      </div>
      <%= f.label "标签" %>
      <div class="tag tagsinput-primary">
        <input name="admin_article[tag_names]" class="tagsinput" data-role="tagsinput" value="<%= @admin_article.tags.map{|t| t.name}.join(',') %>" />
        <!-- <ul class="tag-ul">
            <% @admin_article.tags.each do |t| %>
              <li class="inactive">
                <%= text_field_tag "admin_article[tag_names][]",t.name %>
                <span class="glyphicon glyphicon-remove"></span>
              </li>

            <% end %>
          <li class="current_input_tag">
            <%= text_field_tag "admin_article[tag_names][]",nil %>
          </li>
        </ul> -->
      </div>
      

      <%= f.label "所属类型" %>
      <div class="type">
        <%= f.select(:article_type_id,@all_article_types,{},{class:"form-control select select-primary"}) %>
      </div>
    </div>
<% end %>

app/views/admin/articles/_form_ckeditor.html.erb
<%= form_for(@admin_article) do |f| %>
    <%= form_errors(@admin_article) %>

    <div class="main-form">
        <div class="form-group">
          <%= f.text_field :title, class:"form-control",placeholder:"请输入标题" %>
        </div>
        <div class="form-group">
          <%= f.cktext_area :content, :ckeditor => {:uiColor => '#333333', :toolbar => 'medium',:language => 'en',:height => 300} %>
        </div>
        <%= f.text_field :editor,value: 1,class:"sr-only" %>
        <div class="form-group action">
          <%= link_to '取消', admin_articles_path,class:"btn btn-default cancle" %>
          <%= f.submit class:"btn btn-primary submit",id:"submit" %>
        </div>
    </div>
    <div class="related-form">
      <%= f.label "分类" %>
      <div class="category form-group">
        <% @all_categories.each do |c| %>
          <label class="checkbox">
            <!-- <%= ("&nbsp&nbsp"*c.level).html_safe %> -->
            <%= check_box_tag "admin_article[category_ids][]",c.id,@admin_article.categories.include?(c),{multiple:true,'data-toggle' => "checkbox"} %><%= ">>"*c.level %><b><%= c.name %></b><br>
          </label>
        <% end %>
      </div>
      <%= f.label "标签" %>
      <div class="tag tagsinput-primary">
        <input name="admin_article[tag_names]" class="tagsinput" data-role="tagsinput" value="<%= @admin_article.tags.map{|t| t.name}.join(',') %>" />
        <!-- <ul class="tag-ul">
            <% @admin_article.tags.each do |t| %>
              <li class="inactive">
                <%= text_field_tag "admin_article[tag_names][]",t.name %>
                <span class="glyphicon glyphicon-remove"></span>
              </li>

            <% end %>
          <li class="current_input_tag">
            <%= text_field_tag "admin_article[tag_names][]",nil %>
          </li>
        </ul> -->
      </div>
      

      <%= f.label "所属类型" %>
      <div class="type">
        <%= f.select(:article_type_id,@all_article_types,{},{class:"form-control select select-primary"}) %>
      </div>
    </div>
<% end %>

app/views/admin/articles/edit.html.erb
<% if @admin_article.editor == 0 %>
  <%= render 'form' %>
<% elsif @admin_article.editor == 1 %>
  <%= render 'form_ckeditor' %>
<% end %>

app/views/admin/articles/index.html.erb
<p id="notice"></p>

<div class="panel panel-default table-responsive"> 
  <div class="panel-heading">博文列表</div>

  <table class="table table-hover">
    <thead>
      <tr>
        <th class="text-center" width="20px"><label class="checkbox no-label toggle-all"><input type="checkbox" value=""data-toggle="checkbox"></label></th>
        <th>标题</th>
        <!-- <th>所属分类</th>
        <th>所属标签</th> -->

        <th>发表时间</th>
        <th>状态</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @admin_articles.each do |admin_article| %>
        <tr class="article-index">
          <td class="text-center"><label class="checkbox no-label"><input type="checkbox" value="" data-toggle="checkbox"></label></td>

          <td class="article-title">
            <%= link_to  edit_admin_article_path(admin_article),   title:admin_article.title do %>
              <span class="label label-primary"><%= admin_article.title %></span>
            <% end %>
          </td>
          <!-- <td class="article-category">
            <% admin_article.categories.each do |c| %>
              <%= link_to "/admin/category/#{c.name}" do %>
                <span class="label label-default"><%= c.name %></span>
              <% end %>
            <% end %>
          </td>
          <td class="article-tag">
            <% admin_article.tags.each do |t| %>
              <%= link_to "/admin/tag/#{t.name}" do %>
                <span class="label label-default"><%= t.name %></span>
              <% end %>
            <% end %>
          </td> -->
          <td class="article-created_at"><%= DateTime.parse(admin_article.created_at.to_s).strftime('%Y-%m-%d') %></td>
          <td class="article-state">
            <span class="label label-primary"><%= admin_article.state %></span>
          </td>
          <td class="text-center">
            <%= link_to admin_article, method: :delete, data: { confirm: '确定删除?' } do %>
              <span class="fui-cross-circle text-danger"></span>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/admin/articles/new.html.erb
<% if @editor_type == 0 %>
  <%= render 'form' %>
<% elsif @editor_type == 1 %>
  <%= render 'form_ckeditor' %>
<% end %>

app/views/admin/articles/show.html.erb
<%= markdown @admin_article.title %>
<%= markdown @admin_article.content %>