config/routes.rb
Rails.application.routes.draw do


  mount Ckeditor::Engine => '/ckeditor'
  namespace :index do
    get 'home/index'
    get 'article/:title' => 'home#show',title: /[^\/]+/,as: :article
  end

  root 'index/home#index'
  get '/u/:user' => "index/users#index"
  get '/u/:user/tag/:name' => "index/users#tag"
  get '/u/:user/category/:name' => 'index/users#category'
  post '/search' => 'index/home#search'
  post '/search/:user' => 'index/users#search'
  get '/article-type/:name' => 'index/home#article_type'
  namespace :manage do
    get '/' => "index#index"
    get 'login' => 'session#new'
    post 'login' => 'session#create'
    delete 'login' => 'session#destroy'
    resources :users
    resources :authors
    resources :article_types
  end

  namespace :admin do
    get '/' => "index#index"
    get 'index/index'
    get 'login' => 'session#new'
    post 'login' => 'session#create'
    delete 'logout' => 'session#destroy'
    get 'category/:name' => 'articles#category'
    get 'tag/:name' => 'articles#tag'
    get 'archive/:year/:month' => 'articles#archive'
    resources :archives
    resources :categories
    resources :tags
    resources :articles
    resources :messages
    resources :authors,only:[:index,:edit,:update,:show]
    get 'repassword' => 'authors#repassword'
    post 'repassword' => 'authors#update_password'
    post 'mdtools/preview' => 'mdtools#preview'
  end

  namespace :api do
    post 'push_article' => 'article#index'
  end
end

app/controllers/index/home_controller.rb
class Index::HomeController < IndexController
  def index
    @all_articles = Admin::Article.all.order("created_at DESC").page(params[:page]).per(8)
  end
  def show
    @article = Admin::Article.find_by_title(params[:title])
    @article.update(watch_count:@article.watch_count+1)
  end

  def article_type
    article_type = Admin::ArticleType.find_by_name(params[:name])
    @all_articles = article_type.articles.page(params[:page]).per(8) if article_type
    render 'index'
  end
  def search
    keywords = params[:keywords]
    @all_articles = Admin::Article.where("title LIKE ?","%#{keywords}%").order("created_at DESC") unless keywords.blank?
    @all_categories = Admin::Category.where("name LIKE ?","%#{keywords}%").order("created_at DESC") unless keywords.blank?
    @all_tags = Admin::Tag.where("name LIKE ?","%#{keywords}%").order("created_at DESC") unless keywords.blank?
    @all_authors = Admin::Author.where("name LIKE ?","%#{keywords}%").order("created_at DESC") unless keywords.blank?
  end
end

app/helpers/index/home_helper.rb
module Index::HomeHelper
end

app/views/index/home/index.html.erb
<div class="line"></div>
<% if !@all_articles.nil? %>
  <% @all_articles.each do |a| %>
      <section class="article">
        <div class="time-line">
          <div class="article-type">
            <!-- <span class="glyphicon glyphicon-<%= a.article_type.glyphicon %>"></span> -->
            <img src="/assets/img/icons/<%= a.article_type.glyphicon %>.svg">
          </div>
          <div class="article-date">
            <%= DateTime.parse(a.created_at.to_s).strftime('%Y-%m-%d') %>
          </div>
          <div class="article-author">
            <%= link_to "/u/#{a.author.name}" do %>
            <%= image_tag(a.author.avatar_url(:thumb)) if a.author&&a.author.avatar? %>
            <span><%= a.author.name if a.author %></span>
            <% end %>
          </div>
        </div>
        <div class="article-main">
          <div class="article-title">
            <h1><%= link_to a.title,index_article_path(a.title) %></h1>
          </div>
          <div class="article-content">
            <%= a.abstract.gsub(/<\/?.*?>/,"") %>
          </div>
          <div class="article-footer">
            <div class="footer-item left">
              <a href="<%= index_article_path(a.title)  %>">
                <i class="glyphicon glyphicon-eye-open"></i>
                <span><%= a.watch_count %><span>
              </a>
            </div>
            <div class="footer-item left">
              <a href="<%= index_article_path(a.title)+"#comment" %>">
                <i class="glyphicon glyphicon-comment"></i>
                <span class="ds-thread-count" id="<%= "comment#{a.id}" %>">
                  <script type="text/javascript">
                  var duoshuoQuery = {short_name:"lisiur",id:<%= a.id %>};
                  (function() {
                    var url = "http://api.duoshuo.com/threads/counts.jsonp?short_name="+duoshuoQuery.short_name+"&threads="+duoshuoQuery.id+ "&callback=?"
                    $.getJSON(url,function(data){
                      comment_count = data.response["<%= a.id %>"].comments;
                      currentEleId = "#comment"+<%= a.id %>
                      $(currentEleId).append(comment_count);
                    });
                  })();
                  </script>
                </span>
              </a>
            </div>
            <div class="footer-item right">
              <% a.tags.each do |t| %>
                <%= link_to "/u/#{a.author.name}/tag/#{t.name}",class:"article-tag" do %>
                  <span class="label label-primary"><%= t.name %></span>
                <% end %>
              <% end %>
            </div>
          </div>
        </div>
      </section>
  <% end %>
<% else %>
  <%= render html:'<div class="not-found">未找到相关文章！</div>'.html_safe %>
<% end %>
<div class="pagination-wrap">
<!-- <div class="pagination pagination-minimal">
  <ul>
    <li class="previous"><a href="#fakelink" class="fui-arrow-left"></a></li>
    <li class="active"><a href="#fakelink">1</a></li>
    <li><a href="#fakelink">2</a></li>
    <li><a href="#fakelink">3</a></li>
    <li><a href="#fakelink">4</a></li>
    <li><a href="#fakelink">5</a></li>
    <li><a href="#fakelink">6</a></li>
    <li><a href="#fakelink">7</a></li>
    <li><a href="#fakelink">8</a></li>
    <li><a href="#fakelink">9</a></li>
    <li><a href="#fakelink">10</a></li>
    <li class="pagination-dropdown dropup">
      <a href="#fakelink" class="dropdown-toggle" data-toggle="dropdown">
        <i class="fui-triangle-up"></i>
      </a>
      <ul class="dropdown-menu">
        <li><a href="#fakelink">10–20</a></li>
        <li><a href="#fakelink">20–30</a></li>
        <li><a href="#fakelink">40–50</a></li>
      </ul>
    </li>
    <li class="next"><a href="#fakelink" class="fui-arrow-right"></a></li>
  </ul> -->
  <%= paginate @all_articles %>
</div>
</div>

app/views/index/home/search.html.erb
<!-- 最新的 Bootstrap 核心 JavaScript 文件 -->
<script src="//cdn.bootcss.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
<div class="search-result">

  <!-- Nav tabs -->
  <ul class="nav nav-tabs nav-justified" role="tablist">
    <li role="presentation" class="active"><a href="#article" aria-controls="article" role="tab" data-toggle="tab">文章</a></li>
    <li role="presentation"><a href="#author" aria-controls="author" role="tab" data-toggle="tab">用户</a></li>
    <!-- <li role="presentation"><a href="#category" aria-controls="category" role="tab" data-toggle="tab">分类</a></li>
    <li role="presentation"><a href="#tag" aria-controls="tag" role="tab" data-toggle="tab">标签</a></li> -->
  </ul>

  <!-- Tab panes -->
  <div class="tab-content">
    <div role="tabpanel" class="tab-pane active in fade" id="article">
      <% @all_articles.each do |a| %>
        <%= link_to a.title, index_article_path(a.title) %>
      <% end %>
    </div>
    <div role="tabpanel" class="tab-pane fade" id="author">
      <% @all_authors.each do |a| %>
        <%= link_to a.name, "/u/#{a.name}" %>
      <% end %>
    </div>
    <!-- <div role="tabpanel" class="tab-pane fade" id="category">
      <% @all_categories.each do |c| %>
        <%= link_to c.name, "/" %>
      <% end %>
    </div>
    <div role="tabpanel" class="tab-pane fade" id="tag">
      <% @all_tags.each do |t| %>
        <%= t.name %>
      <% end %>
    </div> -->
  </div>

</div>

app/views/index/home/show.html.erb
<div class="line"></div>

<section id="show-article" class="article">
  <div class="time-line">
    <div class="article-type">
      <!-- <span class="glyphicon glyphicon-<%= @article.article_type.glyphicon %>"></span> -->
      <img src="/assets/img/icons/<%= @article.article_type.glyphicon %>.svg">
    </div>
    <div class="article-date">
      <%= DateTime.parse(@article.created_at.to_s).strftime('%Y-%m-%d') %>
    </div>
    <div class="article-author">
      <%= link_to "/u/#{@article.author.name}" do %>
        <%= image_tag(@article.author.avatar_url(:thumb)) if @article.author&&@article.author.avatar? %>
        <span><%= @article.author.name if @article.author %></span>
      <% end %>
    </div>

  </div>
  <div class="article-main">
    <div class="article-title">
      <h1><%= @article.title %></h1>
    </div>
    <div class="article-content">
      <%= markdown @article.content if @article.editor ==0 %>
      <%= raw @article.content.html_safe if @article.editor ==1 %>
    </div>
  </div>
</section>
<a name="comment"></a>
<!-- 多说评论框 start -->
	<div class="ds-thread" data-thread-key="<%= @article.id %>" data-title="<%= @article.title %>" data-url="<%= index_article_path(@article.title) %>"></div> 
<!-- 多说评论框 end -->
<!-- 多说公共JS代码 start (一个网页只需插入一次) -->
<script type="text/javascript"> 
var duoshuoQuery = {short_name:"lisiur"}; 
	(function() { 
	 var ds = document.createElement('script'); 
		ds.type = 'text/javascript';ds.async = true; 
		ds.src = (document.location.protocol == 'https:' ? 'https:' : 'http:') + '//static.duoshuo.com/embed.js'; 
		ds.charset = 'UTF-8'; 
	 	(document.getElementsByTagName('head')[0]
	 	 || document.getElementsByTagName('body')[0]).appendChild(ds); 
	 })();
	</script> 
<!-- 多说公共JS代码 end -->