config/routes.rb
Rails.application.routes.draw do


  mount Ckeditor::Engine => '/ckeditor'
  namespace :index do
    get 'home/index'
    get 'article/:title' => 'home#show',title: /[^\/]+/,as: :article
  end

  root 'index/home#index'
  get '/u/:user' => "index/users#index"
  get '/u/:user/tag/:name' => "index/users#tag"
  get '/u/:user/category/:name' => 'index/users#category'
  post '/search' => 'index/home#search'
  post '/search/:user' => 'index/users#search'
  get '/article-type/:name' => 'index/home#article_type'
  namespace :manage do
    get '/' => "index#index"
    get 'login' => 'session#new'
    post 'login' => 'session#create'
    delete 'login' => 'session#destroy'
    resources :users
    resources :authors
    resources :article_types
  end

  namespace :admin do
    get '/' => "index#index"
    get 'index/index'
    get 'login' => 'session#new'
    post 'login' => 'session#create'
    delete 'logout' => 'session#destroy'
    get 'category/:name' => 'articles#category'
    get 'tag/:name' => 'articles#tag'
    get 'archive/:year/:month' => 'articles#archive'
    resources :archives
    resources :categories
    resources :tags
    resources :articles
    resources :messages
    resources :authors,only:[:index,:edit,:update,:show]
    get 'repassword' => 'authors#repassword'
    post 'repassword' => 'authors#update_password'
    post 'mdtools/preview' => 'mdtools#preview'
  end

  namespace :api do
    post 'push_article' => 'article#index'
  end
end

app/views/related/admin/_archives.html.erb
<h2 class="title">
  我的归档
  <!--<a href=<%= new_admin_archive_path %> class="link">-->
    <!--<i class="glyphicon glyphicon-plus"></i>-->
  <!--</a>-->
</h2>
<span class="describe">在此可管理你的归档。</span>
<ul>
  <li>
    <a href=<%= admin_archives_path %> class="link">
      <i class="glyphicon glyphicon-th-large"></i>
      <span>所有归档</span>
    </a>
  </li>
</ul>

app/views/related/admin/_articles.html.erb
<h2 class="title">
  我的博文
  <a href=<%= new_admin_article_path %> class="link">
    <i class="glyphicon glyphicon-plus"></i>
  </a>
</h2>
<span class="describe">在此可管理你的博文。</span>
<ul>
  <li>
    <a href=<%= admin_articles_path %> class="link">
      <i class="glyphicon glyphicon-th-large"></i>
      <span>所有博文</span>
    </a>
  </li>

  <li>
    <a href=<%= admin_articles_path+"?unpublished" %> class="link">
      <i class="glyphicon glyphicon-star"></i>
      <span>未发表博文</span>
    </a>
  </li>
  
  <li>
    <%= link_to new_admin_article_path+"?editor=ckeditor" do %>
      <i class="glyphicon glyphicon-star"></i>
      <span>ckeditor</span>
    </a>
    <% end %>
  </li>

  <li>
    <%= link_to new_admin_article_path do %>
      <i class="glyphicon glyphicon-star"></i>
      <span>mdeditor</span>
    </a>
    <% end %>
  </li>
  

</ul>

app/views/related/admin/_authors.html.erb
<h2 class="title">
  个人中心
</h2>
<span class="describe">在此可管理你的个人信息。</span>
<ul>
  <li>
    <a href="<%= admin_authors_path %>" class="link">
      <i class="glyphicon glyphicon-th-large"></i>
      <span>概览</span>
    </a>
  </li>

  <li>
    <a href="<%= edit_admin_author_path(@login_author) %>" class="link">
      <i class="glyphicon glyphicon-star"></i>
      <span>个人设置</span>
    </a>
  </li>

  <li>
    <a href="<%= admin_repassword_path %>" class="link">
      <i class="glyphicon glyphicon-star"></i>
      <span>密码设置</span>
    </a>
  </li>
</ul>

app/views/related/admin/_categories.html.erb
<h2 class="title">
  我的分类
  <a href=<%= new_admin_category_path %> class="link">
    <i class="glyphicon glyphicon-plus"></i>
  </a>
</h2>
<span class="describe">在此可管理你的分类。</span>
<ul>
  <li>
    <a href=<%= admin_categories_path %> class="link">
      <i class="glyphicon glyphicon-th-large"></i>
      <span>所有分类</span>
    </a>
  </li>

  <li>
    <a href="/" class="link sr-only">
      <i class="glyphicon glyphicon-star"></i>
      <span>收藏分类</span>
    </a>
  </li>
</ul>

app/views/related/admin/_index.html.erb
<h2 class="title">
  概览
  <a href="/" class="link">
    <i class="glyphicon glyphicon-plus"></i>
  </a>
</h2>
<span class="describe">在此可快速访问。</span>
<ul>
  <li>
    <a href="/u/<%= @login_author.name %>" class="link">
      <i class="glyphicon glyphicon-th-large"></i>
      <span>我的博客</span>
    </a>
  </li>

  <li>
    <a href="<%= admin_categories_path %>" class="link">
      <i class="glyphicon glyphicon-star"></i>
      <span>我的分类</span>
    </a>
  </li>
</ul>

app/views/related/admin/_messages.html.erb
<h2 class="title">
  我的留言
  <a href="/" class="link">
    <i class="glyphicon glyphicon-plus"></i>
  </a>
</h2>
<span class="describe">在此可管理你的留言。</span>
<ul>
  <li>
    <a href="/" class="link">
      <i class="glyphicon glyphicon-th-large"></i>
      <span>所有留言</span>
    </a>
  </li>
  <li>
    <a href="/" class="link">
      <i class="glyphicon glyphicon-star"></i>
      <span>未处理留言</span>
    </a>
  </li>
</ul>

app/views/related/admin/_tags.html.erb
<h2 class="title">
  我的标签
  <a href=<%= new_admin_tag_path %> class="link">
    <i class="glyphicon glyphicon-plus"></i>
  </a>
</h2>
<span class="describe">在此可管理你的标签。</span>
<ul>
  <li>
    <a href=<%= admin_tags_path %> class="link">
      <i class="glyphicon glyphicon-th-large"></i>
      <span>所有标签</span>
    </a>
  </li>

</ul>