config/routes.rb
Rails.application.routes.draw do


  mount Ckeditor::Engine => '/ckeditor'
  namespace :index do
    get 'home/index'
    get 'article/:title' => 'home#show',title: /[^\/]+/,as: :article
  end

  root 'index/home#index'
  get '/u/:user' => "index/users#index"
  get '/u/:user/tag/:name' => "index/users#tag"
  get '/u/:user/category/:name' => 'index/users#category'
  post '/search' => 'index/home#search'
  post '/search/:user' => 'index/users#search'
  get '/article-type/:name' => 'index/home#article_type'
  namespace :manage do
    get '/' => "index#index"
    get 'login' => 'session#new'
    post 'login' => 'session#create'
    delete 'login' => 'session#destroy'
    resources :users
    resources :authors
    resources :article_types
  end

  namespace :admin do
    get '/' => "index#index"
    get 'index/index'
    get 'login' => 'session#new'
    post 'login' => 'session#create'
    delete 'logout' => 'session#destroy'
    get 'category/:name' => 'articles#category'
    get 'tag/:name' => 'articles#tag'
    get 'archive/:year/:month' => 'articles#archive'
    resources :archives
    resources :categories
    resources :tags
    resources :articles
    resources :messages
    resources :authors,only:[:index,:edit,:update,:show]
    get 'repassword' => 'authors#repassword'
    post 'repassword' => 'authors#update_password'
    post 'mdtools/preview' => 'mdtools#preview'
  end

  namespace :api do
    post 'push_article' => 'article#index'
  end
end

app/models/admin/archive.rb
class Admin::Archive < ActiveRecord::Base
  belongs_to :author
  has_many :articles
end

app/controllers/admin/archives_controller.rb
class Admin::ArchivesController < AdminController
  before_action :set_admin_archive, only: [:show, :edit, :update, :destroy]

  # GET /admin/archives
  # GET /admin/archives.json
  def index
    @admin_archives = @login_author.archives.order("created_at DESC")
  end

  # GET /admin/archives/1
  # GET /admin/archives/1.json
  def show
  end

  # GET /admin/archives/new
  def new
    @admin_archive = Admin::Archive.new
  end

  # GET /admin/archives/1/edit
  def edit
  end

  # POST /admin/archives
  # POST /admin/archives.json
  def create
    @admin_archive = Admin::Archive.new(admin_archive_params)

    respond_to do |format|
      if @admin_archive.save
        format.html { redirect_to @admin_archive, notice: 'Archive was successfully created.' }
        format.json { render :show, status: :created, location: @admin_archive }
      else
        format.html { render :new }
        format.json { render json: @admin_archive.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin/archives/1
  # PATCH/PUT /admin/archives/1.json
  def update
    respond_to do |format|
      if @admin_archive.update(admin_archive_params)
        format.html { redirect_to @admin_archive, notice: 'Archive was successfully updated.' }
        format.json { render :show, status: :ok, location: @admin_archive }
      else
        format.html { render :edit }
        format.json { render json: @admin_archive.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/archives/1
  # DELETE /admin/archives/1.json
  def destroy
    @admin_archive.destroy
    respond_to do |format|
      format.html { redirect_to admin_archives_url, notice: 'Archive was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_admin_archive
      @admin_archive = @login_author.archives.find_by_id(params[:id])
      if @admin_archive.nil?
        render html: "<strong>Not Found</strong>".html_safe and return
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def admin_archive_params
      params.fetch(:admin_archive, {})
    end
end

app/helpers/admin/archives_helper.rb
module Admin::ArchivesHelper
end

app/views/admin/archives/_form.html.erb
<%= form_for(@admin_archive) do |f| %>
  <% if @admin_archive.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@admin_archive.errors.count, "error") %> prohibited this admin_archive from being saved:</h2>

      <ul>
      <% @admin_archive.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/archives/edit.html.erb
<%= render 'form' %>

app/views/admin/archives/index.html.erb
<p id="notice"></p>

<div class="panel panel-default table-responsive"> 
  <div class="panel-heading">归档列表</div>
  <table class="table table-hover">
    <thead>
      <tr>
        <th>归档</th>
        <!-- <th colspan="3"></th> -->
      </tr>
    </thead>

    <tbody>
      <% @admin_archives.each do |admin_archive| %>
        <tr>
          <td><%= link_to "#{admin_archive.year}年#{admin_archive.month}月","/admin/archive/#{admin_archive.year}/#{admin_archive.month}" %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/admin/archives/new.html.erb
<h1>New Admin Archive</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_archives_path %>

app/views/admin/archives/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_admin_archive_path(@admin_archive) %> |
<%= link_to 'Back', admin_archives_path %>